Add upload priority layers
danangmassandy/cplus-plugin pull request #13
Opened 2024-05-29 07:21 UTC by zamuzakki

This is PR for https://github.com/ConservationInternational/cplus-plugin/issues/441

I have tested using several PWL, and give them some weight.
![image](https://github.com/danangmassandy/cplus-plugin/assets/7352963/1337eeea-f091-449a-9e18-733ec0350926)

The API then considers those weight, as indicated in this log

```
[2024-05-29 07:14:39,165: INFO/ForkPoolWorker-3]  Used parameters for calculating weighting activities {'CELLSIZE': 0, 'CRS': None, 'EXPRESSION': '"Alien_Plant_Removal_3aa5@1" + (5.0*"social_int_clip_norm@1") + (2.0*"ei_all_gknp_clip_norm@1") + (5.0*"biocombine_clip_norm_QtBE9kG@1") + (3.0*"Policy_S2nhJ2z@1")', 'EXTENT': '877301.8070349816,1016212.7812331037,7203080.7869933,7345132.766826201 [EPSG:32735]', 'LAYERS': ['/home/web/media/4/77405c03-df4e-4b41-8701-66a21239c3c1/normalized_activities/Alien_Plant_Removal_3aa5.tif', '/home/web/media/4/77405c03-df4e-4b41-8701-66a21239c3c1/priority_layer/social_int_clip_norm.tif', '/home/web/media/4/77405c03-df4e-4b41-8701-66a21239c3c1/priority_layer/ei_all_gknp_clip_norm.tif', '/home/web/media/4/77405c03-df4e-4b41-8701-66a21239c3c1/priority_layer/biocombine_clip_norm_QtBE9kG.tif', '/home/web/media/4/77405c03-df4e-4b41-8701-66a21239c3c1/priority_layer/Policy_S2nhJ2z.tif'], 'OUTPUT': '/home/web/media/4/77405c03-df4e-4b41-8701-66a21239c3c1/weighted_activities/Alien_Plant_Removal_81ef.tif'}
```

I have also set Coefficient for carbon layers in settings. That value and layer is reflected in this log
```
[2024-05-29 07:14:27,953: INFO/ForkPoolWorker-3] Used parameters for combining pathways and carbon layers generation: {'CELLSIZE': 0, 'CRS': None, 'EXPRESSION': '"Final_Avoided_Grassland_priority_norm_new@1" + 1.0 * ("bou_SOC_carbonsum_norm_null_con_clip@1")', 'EXTENT': '877301.8070349816,1016212.7812331037,7203080.7869933,7345132.766826201 [EPSG:32735]', 'LAYERS': ['/home/web/media/4/77405c03-df4e-4b41-8701-66a21239c3c1/ncs_pathway/Final_Avoided_Grassland_priority_norm_new.tif', '/home/web/media/4/77405c03-df4e-4b41-8701-66a21239c3c1/ncs_carbon/bou_SOC_carbonsum_norm_null_con_clip.tif'], 'OUTPUT': 'TEMPORARY_OUTPUT'} 
```

2024-05-29 08:24 UTC, danangmassandy requested changes

2024-05-29 08:24 UTC, danangmassandy commented on src/cplus_plugin/api/scenario_task_api_client.py
> +        priority_layers = settings_manager.get_priority_layers()
please change to self.get_priority_layers()

2024-05-29 08:24 UTC, danangmassandy commented on src/cplus_plugin/api/scenario_task_api_client.py
> +            if priority_layer['uuid'] in activity_pwl_uuids and os.path.exists(priority_layer['path']):
I think it's better to use priority_layer.get so we don't get key error exception. The original code in tasks.py is also using .get('").
Please apply the same when retrieving 'groups' and 'value'.

2024-05-29 08:24 UTC, danangmassandy commented on src/cplus_plugin/api/scenario_task_api_client.py
> +        priority_layers = settings_manager.get_priority_layers()
please change to self.get_priority_layers()

2024-05-29 08:24 UTC, danangmassandy commented on src/cplus_plugin/api/scenario_task_api_client.py
> +            if priority_layer['path'] in self.path_to_layer_mapping:
same as above comment, use priority_layer.get("")

2024-05-30 02:36 UTC, danangmassandy commented
@zamuzakki please help to resolve the conflict and then I will merge this PR! Thank you,

2024-05-30 03:07 UTC, zamuzakki commented
@danangmassandy I've resolved the conflict

2024-05-30 04:43 UTC, danangmassandy approved these changes
Cool, thanks Zakki

2024-05-30 04:43 UTC, merged